### ISSUE TITLE
On Ubuntu 20.04 crashes on load

### ISSUE THREAD

**Issue by andraz** [RedisJSON/RedisJSON#544]
I tried loading it via configuration but it coredumps, can't restart the service.

```
root@lcx:/etc/redis# service redis-server restart
root@lcx:/etc/redis# service redis-server status
● redis-server.service - Advanced key-value store
     Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: core-dump) since Wed 2021-11-17 17:19:23 UTC; 9ms ago
       Docs: http://redis.io/documentation,
             man:redis-server(1)
    Process: 5953 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=0/SUCCESS)
   Main PID: 5954 (code=dumped, signal=ABRT)

Nov 17 17:19:22 lcx systemd[1]: redis-server.service: Main process exited, code=dumped, status=6/ABRT
Nov 17 17:19:22 lcx systemd[1]: redis-server.service: Failed with result 'core-dump'.
Nov 17 17:19:23 lcx systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 5.
Nov 17 17:19:23 lcx systemd[1]: Stopped Advanced key-value store.
Nov 17 17:19:23 lcx systemd[1]: redis-server.service: Start request repeated too quickly.
Nov 17 17:19:23 lcx systemd[1]: redis-server.service: Failed with result 'core-dump'.
Nov 17 17:19:23 lcx systemd[1]: Failed to start Advanced key-value store.
```

Manual load crashes with:

```
root@lcx:/etc/redis# redis-server --loadmodule /etc/redis/modules/rejson.so
5700:C 17 Nov 2021 17:06:12.789 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
5700:C 17 Nov 2021 17:06:12.789 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=5700, just started
5700:C 17 Nov 2021 17:06:12.789 # Configuration loaded
5700:M 17 Nov 2021 17:06:12.790 * Increased maximum number of open files to 10032 (it was originally set to 1024).
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 5.0.7 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 5700
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

5700:M 17 Nov 2021 17:06:12.791 # Server initialized
5700:M 17 Nov 2021 17:06:12.791 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
5700:M 17 Nov 2021 17:06:12.791 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
5700:M 17 Nov 2021 17:06:12.792 * <ReJSON> version: 999999 git sha: 74ed68e branch: master
5700:M 17 Nov 2021 17:06:12.792 * <ReJSON> Exported RedisJSON_V1 API
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/azureuser/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.24.0/src/context/mod.rs:269:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

```
root@lcx:/etc/redis# export RUST_BACKTRACE=full; redis-server --loadmodule /etc/redis/modules/rejson.so
5880:C 17 Nov 2021 17:14:54.409 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
5880:C 17 Nov 2021 17:14:54.409 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=5880, just started
5880:C 17 Nov 2021 17:14:54.410 # Configuration loaded
5880:M 17 Nov 2021 17:14:54.410 * Increased maximum number of open files to 10032 (it was originally set to 1024).
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 5.0.7 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 5880
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

5880:M 17 Nov 2021 17:14:54.412 # Server initialized
5880:M 17 Nov 2021 17:14:54.412 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
5880:M 17 Nov 2021 17:14:54.412 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
5880:M 17 Nov 2021 17:14:54.412 * <ReJSON> version: 999999 git sha: 74ed68e branch: master
5880:M 17 Nov 2021 17:14:54.412 * <ReJSON> Exported RedisJSON_V1 API
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/azureuser/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.24.0/src/context/mod.rs:269:52
stack backtrace:
   0:     0x7f4e378a1e2c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h33e1fc29f9141885
   1:     0x7f4e378cd68f - core::fmt::write::h3b0ec0911656cf8a
   2:     0x7f4e3789da85 - std::io::Write::write_fmt::h015d8bf6ff8e54cc
   3:     0x7f4e378b226b - std::panicking::default_hook::{{closure}}::h8e3df13515f3fd66
   4:     0x7f4e378b1e4f - std::panicking::default_hook::h468fd6be1a9a88b4
   5:     0x7f4e378b2773 - std::panicking::rust_panic_with_hook::h37bd253c0dc6b3b6
   6:     0x7f4e378a2307 - std::panicking::begin_panic_handler::{{closure}}::hff24a561569e53dd
   7:     0x7f4e378a1f6c - std::sys_common::backtrace::__rust_end_short_backtrace::h1e26e0dfac5e461e
   8:     0x7f4e378b2372 - rust_begin_unwind
   9:     0x7f4e377f5b31 - core::panicking::panic_fmt::h134fc7184a83985e
  10:     0x7f4e377f5a7d - core::panicking::panic::hd975c9b2534afa10
  11:     0x7f4e37875e8f - redis_module::context::Context::set_module_options::h4b8df3e8ec624154
  12:     0x7f4e378517c8 - RedisModule_OnLoad
  13:     0x55e5363f5421 - moduleLoad
  14:     0x55e5363f5583 - moduleLoadFromQueue
  15:     0x55e536370a33 - main
  16:     0x7f4e388020b3 - __libc_start_main
  17:     0x55e536370d3e - _start
  18:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

```
root@lcx:/etc/redis# redis-server -v
Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=636cde3b5c7a3923
```

```
root@lcx:/etc/redis# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by oshadmi** [comment]
@andraz  Please use redis version 6+

**Comment by andraz** [comment]
With 6.0 works great, thanks.
