### ISSUE TITLE
JSON to object Get multiple attributes. When getting non-existent attributes, an error occurs

### ISSUE THREAD

**Issue by 501956430** [RedisJSON/RedisJSON#661]
```
127.0.0.1:6379> json.set b . '{"name":"abcd"}'
OK
127.0.0.1:6379> json.get b name age
(error) ERR Path 'age' does not exist`
```
[issues address](https://github.com/dengliming/redis-modules-java/issues/37)

**Comment by oshadmi** [comment]
@501956430 When using standard paths (beginning with `$`) there is no error:
```
127.0.0.1:6379> json.get b $.name $.age
"{\"$.name\":[\"abcd\"],\"$.age\":[]}"

```

Error occurs when using one or more legacy paths (as with ReJSON 1.X)

**Comment by 501956430** [comment]
This method returns an array. How to convert it into an object?
```
redisJSON.get(key,User.class, new GetArgs().path("name", "age"))
```
@oshadmi

**Comment by oshadmi** [comment]
@501956430 You can look at [this](https://github.com/redis/jedis/blob/4.1/src/test/java/redis/clients/jedis/modules/json/RedisJsonV1Test.java#L102) (use `gson`)

**Comment by 501956430** [comment]
```
public class MusicData  {
    private Integer type;
    private String title;
    private String author;
}
```

```
       JReJSON client = new JReJSON();
        client.set("MusicData", new MusicData().setTitle("test").setAuthor("http://"));
       //MusicData={title=test, author=http://}
        System.out.println(client.get("MusicData").toString());
        
       //Object serialization only stores non empty attributes. There is an error in obtaining other non-existent attributes. Is it reasonable?
        Map<String, Object> m = client.get("MusicData", HashMap.class, Path.of("title"), Path.of("type"));
        System.out.println(JSONObject.toJSONString(m));
```

```
redis.clients.jedis.exceptions.JedisDataException: ERR Path 'type' does not exist
	at redis.clients.jedis.Protocol.processError(Protocol.java:132)
	at redis.clients.jedis.Protocol.process(Protocol.java:166)
	at redis.clients.jedis.Protocol.read(Protocol.java:220)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:278)
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:215)
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:205)
	at com.redislabs.modules.rejson.JReJSON.get(JReJSON.java:246)
```
@oshadmi

**Comment by sazzad16** [comment]
@501956430 Following is using Jedis 4.1.1

Code:
```
    UnifiedJedis jedis = ...;
    System.out.println(jedis.jsonSetWithEscape("MusicData", getData()));
    System.out.println(jedis.jsonGet("MusicData", Path2.of("title"), Path2.of("type")));
```

Output:
```
OK
{"$.type":[],"$.title":["test"]}
```

**Comment by 501956430** [comment]
@sazzad16 How to do this with jrejson?

**Comment by sazzad16** [comment]
@501956430 

> @sazzad16 How to do this with jrejson?

```
    client.set("MusicData", getData());
    System.out.println(client.get("MusicData", Object.class, Path.of("$.title"), Path.of("$.type")));
```

```
{$.type=[], $.title=[test]}
```

**Comment by 501956430** [comment]
@sazzad16 Can such a structure be converted into an entity object?

**Comment by sazzad16** [comment]
@501956430 This is the most I can do at this moment.

**Comment by 501956430** [comment]
@oshadmi @sazzad16  When getting non-existent attributes, you should return null instead of throwing exceptions. In the actual use scenario, it is not friendly. What do you think?
